### PR TITLE
Fix unassigned variables

### PR DESCRIPTION
**Pull request by foochuanwei**
I am not too sure about replacing this:
```
sudo sed -i -e "s/${whoami}:\/bin\/bash/${whoami}:\/usr\/bin\/zsh/" \
     /etc/passwd`
```
with this:
```
sudo sed -i -e "s/$(whoami):\/bin\/bash/$(whoami):\/usr\/bin\/zsh/" \
     /etc/passwd`
```
Can someone confirm that it's correct?

### CODE REVIEW

**Comment by foochuanwei** [comment]
@anassinator I'm quite inexperienced with sed.

**Comment by anassinator** [comment]
Have you confirmed it works now?

**Comment by foochuanwei** [comment]
Yes it works.

**Comment by anassinator** [comment]
Good enough for me

**Pull request merged**
